// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValueCo.CashUpApi.Data;

#nullable disable

namespace ValueCo.CashUpApi.Migrations
{
    [DbContext(typeof(CashUpDbContext))]
    [Migration("20260320070110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValueCo.CashUpApi.Models.CashUpDay", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<DateOnly>("CashUpDate")
                        .HasColumnType("date");

                    b.Property<string>("CashUpNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ChangeBoxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountingBanking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FNB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Floats")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LooseChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PettyCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PettyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Surrender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DayId");

                    b.HasIndex("StoreId", "CashUpDate")
                        .IsUnique();

                    b.ToTable("CashUpDays");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.CashierRow", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<decimal>("Card")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Coupon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<decimal>("EFT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Erase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gift")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Loyalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Returns")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RowId");

                    b.HasIndex("DayId");

                    b.ToTable("CashierRows");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.EFTDetail", b =>
                {
                    b.Property<int>("EFTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EFTId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EFTDate")
                        .HasColumnType("date");

                    b.Property<string>("SONumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EFTId");

                    b.HasIndex("DayId");

                    b.ToTable("EFTDetails");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StoreId");

                    b.HasIndex("StoreCode")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.CashUpDay", b =>
                {
                    b.HasOne("ValueCo.CashUpApi.Models.Store", "Store")
                        .WithMany("CashUpDays")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.CashierRow", b =>
                {
                    b.HasOne("ValueCo.CashUpApi.Models.CashUpDay", "CashUpDay")
                        .WithMany("CashierRows")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashUpDay");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.EFTDetail", b =>
                {
                    b.HasOne("ValueCo.CashUpApi.Models.CashUpDay", "CashUpDay")
                        .WithMany("EFTDetails")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashUpDay");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.CashUpDay", b =>
                {
                    b.Navigation("CashierRows");

                    b.Navigation("EFTDetails");
                });

            modelBuilder.Entity("ValueCo.CashUpApi.Models.Store", b =>
                {
                    b.Navigation("CashUpDays");
                });
#pragma warning restore 612, 618
        }
    }
}
